d = input ('Digite algo: ')
print('O tipo primitivo desse valor é ',type(d))
print('So tem espaços: ', d.isspace())
print('Só tem números', d.isnumeric())
print('É um alfabetico: ', d.isalpha())
print('É um alfabúmerico', d.isalnum())
print('Esta em MAIUSCULA: ', d.isupper())
print('Está em minuscula: ', d.islower())
print('Está Capitalizada', d.istitle())